### ISSUE TITLE
Unable to update if the release channel got changed

### ISSUE THREAD

**Issue by Czekoloczek** [pyoncord/BunnyManager#18]
After changing the release channel from alpha to beta (and waiting for the beta updates) Bunny manager still shows that it cannot downgrade, even when it'll update (from 239.7 - alpha to 239.10 - beta)

![Screenshot_20240718_004428_Bunny Manager.png](https://github.com/user-attachments/assets/1f578f5f-fc48-400e-987e-b4546bbc4fd1)

**Comment by coolesding** [comment]
this is only while on the same major version, when discord releases beta 240.x it will be able to update, ive seen this issue before and i guess it's something that wont be fixed, though maybe it would be a good idea to indicate in this case that itll be able to update when the newer version releases

**Comment by amsyarasyiq** [comment]
This can't be fixed, Discord's style of assigning version code is: [major][channel][minor]
Convert the version name to version code, we'll have 239207 > 239110
Android will consider it a downgrade, although it's actually an upgrade
Wait for next Discord's major patch which you can switch to any channel as you wish
