### ISSUE TITLE
Auto-update Discord 

### ISSUE THREAD

**Issue by expected-ingot** [pyoncord/BunnyManager#19]
I keep getting "New Discord version!" messages and would like a setting that automatically patches and updates Discord, and (optionally) disables auto updating while on mobile data.

**Comment by Ushie** [comment]
This isn't possible, patching Discord is a resource heavy action and isn't something that can simply be done in the background

The app would also not know when is an appropriate time to auto update it

**Comment by expected-ingot** [comment]
1. maybe make it only when charging?
2. device idle, charging, not using discord for more than half an hour or hour, not in a call...

**Comment by amsyarasyiq** [comment]
still not possible... we can't just silently patch and install apps in the background. i doubt we can even tell the user's battery in the background, let alone knowing how long since user have used discord
