### ISSUE TITLE
[Feature Request] Is it possible to allow the download and patch of a specified version?

### ISSUE THREAD

**Issue by prpjzz** [pyoncord/BunnyManager#22]
Hello ~

I'm the one who likes to use older versions of Discord, particularly v205.15 (the last version allowed to use older interfaces), and some of the stable versions that I find stable in higher versions, but is not a latest version.

Although I can patch Discord using LSPatch with BunnyXposed for use, this has some problems like I can't quickly change the Discord package id to io.github.pyoncord.app, but have to use a third-party tool as well.

Can you allow manual patching of a user-assigned version (Apk file will be required for a version patched in this style)? Or download a user-defined version, if that's what the user wants.

Hope you can answer. Thank you and have a nice day.

**Comment by Ushie** [comment]
This feature is available in the Developer Settings. To enable it, tap the app version on the About page 10 times. Once enabled, you can access the settings page to specify the Discord version (using the version code, not the version name).
![image](https://github.com/user-attachments/assets/2ce3f835-2034-461e-9a75-4498e6ff8307)
