### ISSUE TITLE
Play Protect started marking Bunny Manager app for Harmful App

### ISSUE THREAD

**Issue by RoonMoonlight** [pyoncord/BunnyManager#24]
With the last release of Bunny Manager, Play Protect started marking Bunny Manager as 'harmful app' on Android. I am using Android 14 One UI 6 and model Galaxy S22+.

**Comment by Rico040** [comment]
This is false positive.

**Comment by RoonMoonlight** [comment]
I know, just wanted to post here in case if there is any solution (I know the temp workaround tho, that you should disable Play Protect on settings)

**Comment by MrK004** [comment]
I disabled and enabled Play Protect again and now somehow it is fine.

![Screenshot_20240909_073438_Google Play Store.png](https://github.com/user-attachments/assets/8fb373c8-0e50-470a-bc90-934a5e0c3001)
