### ISSUE TITLE
[Request] Option to use original discord package name

### ISSUE THREAD

**Issue by Polyeith** [pyoncord/BunnyManager#28]
Would be cool to be able to use the original com.discord package name, essentially because YouTube has it in their share menu by default.

**Comment by breadcat0314** [comment]
You can change the package name by accessing the developer settings in the manager.

**Comment by Polyeith** [comment]
I don't know if I'm missing something, but how do you get into developer settings? Can't seem to find an option for it

**Comment by Polyeith** [comment]
Nevermind, figured it out. Just gotta tap the version number a couple times. Thanks 👍.
