### ISSUE TITLE
Clicking update notification should open changelog, not autostart the update

### ISSUE THREAD

**Issue by KaKi87** [pyoncord/BunnyManager#6]
Thanks

**Comment by rennpy** [comment]
The whole point of an update notification is to get an easy way to install without opening the app. If you want the changelog, open the manager. So, changing this already useful feature just for your convenience is quite a waste of time.

**Comment by Rico040** [comment]
Can you clarify a bit, what's kind of changelog you wanna see?

**Comment by rennpy** [comment]
They just want the update changelog, you can literally see it by opening the app (if it wasnt clear enough already)

**Comment by Rairof** [comment]
Similar to this perhaps-
![Screenshot_20240515-135606](https://github.com/pyoncord/BunnyManager/assets/107706560/9a70ee17-a44c-40f0-bc8f-38df7f4cc131)

**Comment by rennpy** [comment]
Yes, but this opens the app, which ruins the direct install for everyone which is such a nice thing to have 😭

**Comment by Rairof** [comment]
https://github.com/pyoncord/BunnyManager/issues/6#issuecomment-2111541797
Agreed, this not needed.

**Comment by amsyarasyiq** [comment]
Discord doesn't post changelogs whatsoever

**Comment by KaKi87** [comment]
Sorry I didn't notice it was about Discord and not Bunny.

Still, clicking the notification shouldn't automatically start the update, but rather open the Bunny app homepage that shows the current version, the latest version, and the update button.

Thanks

**Comment by rushiiMachine** [comment]
tbh, clicking the notification itself shouldn't autostart an expensive operation 
instead it should use a notification button

**Comment by wingio** [comment]
> tbh, clicking the notification itself shouldn't autostart an expensive operation instead it should use a notification button

the notification tells you what will happen when you click it

**Comment by KaKi87** [comment]
That's not displayed in collapsed mode.

**Comment by rushiiMachine** [comment]
> the notification tells you what will happen when you click it

not really an excuse unless the notification was prompted by the user (ie, download ready, click to install)
 it might be collapsed, or you might fat finger it and start downloading new apk on limited mobile data
