### ISSUE TITLE
[Feature Request] Please add an in-built Applock 

### ISSUE THREAD

**Issue by Mathew20kdroid** [pyoncord/BunnyManager#7]
Please add an in-built Applock for the Bunny Discord app......

**Comment by CiannieTheBottom** [comment]
just use any applocking app like applock

**Comment by Mathew20kdroid** [comment]
Well tried that, all 3rd party Applock sucks, too laggy and unresponsive...

Also most phones don't come with an In-built Applock

**Comment by Mathew20kdroid** [comment]
Or it would be better if we have the option to lock specific channels/servers in our Discord.....

**Comment by amsyarasyiq** [comment]
Out of Bunny's scope. Could be a plugin, but this is not a place for plugin requests.
